# Generated by Django 5.1.8 on 2026-07-21 06:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('values', 'Core Values'), ('communication', 'Communication Style'), ('conflict', 'Conflict Resolution'), ('love_language', 'Love Language'), ('lifestyle', 'Lifestyle Pace'), ('ambition', 'Ambition & Goals')], max_length=20)),
                ('question_type', models.CharField(choices=[('scale_1_5', 'Scale 1-5'), ('multiple_choice', 'Multiple Choice'), ('slider', 'Slider')], default='scale_1_5', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='For multiple-choice questions')),
                ('weight', models.FloatField(default=1.0, help_text='Category weight for scoring')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compatibility_questions',
                'ordering': ['order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='CompatibilityResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category_scores', models.JSONField(default=dict, help_text='Per-category breakdown')),
                ('explanation', models.TextField(blank=True, default='')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compatibility_results',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_answers',
                'ordering': ['question__order'],
            },
        ),
    ]
