# Generated by Django 5.1.8 on 2026-07-21 06:00

import django.core.validators
import profiles.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('hobby', 'Hobby'), ('sport', 'Sport'), ('music', 'Music'), ('food', 'Food'), ('travel', 'Travel'), ('film', 'Film & TV'), ('art', 'Art'), ('tech', 'Technology'), ('lifestyle', 'Lifestyle'), ('values', 'Values')], default='hobby', max_length=20)),
            ],
            options={
                'db_table': 'interests',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=profiles.models.photo_upload_path)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'photos',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('O', 'Other')], max_length=2)),
                ('gender_preference', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('O', 'Other'), ('A', 'All')], default='A', max_length=2)),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('education', models.CharField(blank=True, default='', max_length=200)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True)),
                ('relationship_goal', models.CharField(choices=[('long_term', 'Long-term relationship'), ('short_term', 'Short-term dating'), ('friendship', 'Friendship'), ('unsure', 'Not sure yet')], default='unsure', max_length=20)),
                ('lifestyle_tags', models.JSONField(blank=True, default=list, help_text="e.g. ['non-smoker', 'social-drinker', 'vegetarian']")),
                ('personality_tags', models.JSONField(blank=True, default=list)),
                ('profile_completion_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.interest')),
            ],
            options={
                'db_table': 'profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
